### ISSUE TITLE
Examples in README doesn't work

### ISSUE THREAD

**Issue by solnic** [dkubb/axiom#4]
Hey Dan just a heads up that I tried examples from the readme and got this:

```
ruby-1.9.2-p290 :003 > relation = Veritas::Relation.new([ [ :id, Integer ] ], [ [ 1 ] ])
 => #<Veritas::Relation::Materialized:0x007fc6a0b0c818 @header=[<Attribute::Integer name: id>], @tuples=[[1]], @directions=#<Veritas::Relation::Operation::Order::DirectionSet:0x007fc6a2945d70 @directions=[], @__memory={}>, @__memory={}> 
ruby-1.9.2-p290 :004 > new_relation = relation.project([ :a, :b, :c ])
NoMethodError: undefined method `to_sym' for nil:NilClass
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/attribute.rb:115:in `initialize'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/support/immutable.rb:213:in `new'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/support/immutable.rb:213:in `new'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/support/abstract_class.rb:37:in `new'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/attribute.rb:63:in `coerce'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/relation/header.rb:42:in `block in coerce_attributes'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/relation/header.rb:42:in `map'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/relation/header.rb:42:in `coerce_attributes'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/relation/header.rb:29:in `new'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/relation/header.rb:286:in `new'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/relation/header.rb:145:in `project'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/algebra/projection.rb:22:in `initialize'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/support/immutable.rb:213:in `new'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/support/immutable.rb:213:in `new'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/relation.rb:59:in `new'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/algebra/projection.rb:133:in `project_relation'
    from /Users/solnic/.rvm/gems/ruby-1.9.2-p290@veritas/bundler/gems/veritas-945ff60005b9/lib/veritas/algebra/projection.rb:90:in `project'
    from (irb):4
```

**Comment by dkubb** [comment]
@solnic good call. I never intended those to be executable as-is, but maybe I should have. It would be nice if those were more than examples to look at, and actually executed.

**Comment by solnic** [comment]
@dkubb in virtus I started writing specs for examples from readme file. They are not a part of the main spec suite, but I run them before making a new release.

**Comment by dkubb** [comment]
This is now resolved.
