### ISSUE TITLE
undefined local variable or method `include_comparison_methods'

### ISSUE THREAD

**Issue by acook** [dkubb/axiom#53]
Error when attempting to use Axiom:

```
/Users/acook/.rvm/gems/ruby-2.1.1@rom/gems/axiom-0.1.1/lib/axiom/support/equalizer.rb:18:in `initialize': undefined local variable or method `include_comparison_methods' for #<Axiom::Equalizer:0x007fa94bd5d698> (NameError)
        from /Users/acook/.rvm/gems/ruby-2.1.1@rom/gems/axiom-0.1.1/lib/axiom/support/operation/binary.rb:6:in `new'
        from /Users/acook/.rvm/gems/ruby-2.1.1@rom/gems/axiom-0.1.1/lib/axiom/support/operation/binary.rb:6:in `<module:Binary>'
        from /Users/acook/.rvm/gems/ruby-2.1.1@rom/gems/axiom-0.1.1/lib/axiom/support/operation/binary.rb:5:in `<module:Operation>'
        from /Users/acook/.rvm/gems/ruby-2.1.1@rom/gems/axiom-0.1.1/lib/axiom/support/operation/binary.rb:4:in `<module:Axiom>'
        from /Users/acook/.rvm/gems/ruby-2.1.1@rom/gems/axiom-0.1.1/lib/axiom/support/operation/binary.rb:3:in `<top (required)>'
        from /Users/acook/.rvm/gems/ruby-2.1.1@rom/gems/axiom-0.1.1/lib/axiom.rb:90:in `require'
        from /Users/acook/.rvm/gems/ruby-2.1.1@rom/gems/axiom-0.1.1/lib/axiom.rb:90:in `<top (required)>'
        from /Users/acook/.rvm/gems/ruby-2.1.1@rom/gems/rom-relation-0.1.2/lib/rom-relation.rb:10:in `require'
        from /Users/acook/.rvm/gems/ruby-2.1.1@rom/gems/rom-relation-0.1.2/lib/rom-relation.rb:10:in `<top (required)>'
        from /Users/acook/.rvm/gems/ruby-2.1.1@rom/gems/rom-0.1.2/lib/rom.rb:4:in `require'
        from /Users/acook/.rvm/gems/ruby-2.1.1@rom/gems/rom-0.1.2/lib/rom.rb:4:in `<top (required)>'
        from ./run_me.rb:6:in `require'
        from ./run_me.rb:6:in `<main>'
```

Sample project to reproduce bug: https://gist.github.com/acook/dbaa454f21681b4d27cd

**Comment by solnic** [comment]
sorry about this; it's fixed on edge, I'll push a release...soon

**Comment by acook** [comment]
Ah, using head versions of everything (rom, axiom, axiom-memory-adapter) does work. Looking forward to updated released gems.

**Comment by dkubb** [comment]
@solnic was it a bug in axiom, or somewhere else?

**Comment by acook** [comment]
@dkubb It looks like a bug in Axiom's integration with Equalizer. It seems it was fixed [in this commit](https://github.com/dkubb/axiom/commit/db6c80f8ab37ef2ff48fd74789e781fb75f894f1#diff-279b04545b220b6dd70ab26a7412a2d5) 4 months ago, but the latest released code (on January 2014) doesn't seem to include the change.

**Comment by solnic** [comment]
It wasn't a bug; equalizer had a breaking change and that's it.
